package org.zhangmz.cymbidium.fileservice.orm.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

@Table(name = "fileinfos")
public class Fileinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfos.id
     *
     * @mbggenerated Wed Apr 13 15:47:13 CST 2016
     */
    @Id
    @Column(name = "Id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfos.file_name
     *
     * @mbggenerated Wed Apr 13 15:47:13 CST 2016
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfos.file_path
     *
     * @mbggenerated Wed Apr 13 15:47:13 CST 2016
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfos.enduser_id
     *
     * @mbggenerated Wed Apr 13 15:47:13 CST 2016
     */
    private Long enduserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfos.group_id
     *
     * @mbggenerated Wed Apr 13 15:47:13 CST 2016
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfos.save_date
     *
     * @mbggenerated Wed Apr 13 15:47:13 CST 2016
     */
    private Date saveDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfos.status
     *
     * @mbggenerated Wed Apr 13 15:47:13 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfos.note
     *
     * @mbggenerated Wed Apr 13 15:47:13 CST 2016
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfos.id
     *
     * @return the value of fileinfos.id
     *
     * @mbggenerated Wed Apr 13 15:47:13 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfos.id
     *
     * @param id the value for fileinfos.id
     *
     * @mbggenerated Wed Apr 13 15:47:13 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfos.file_name
     *
     * @return the value of fileinfos.file_name
     *
     * @mbggenerated Wed Apr 13 15:47:13 CST 2016
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfos.file_name
     *
     * @param fileName the value for fileinfos.file_name
     *
     * @mbggenerated Wed Apr 13 15:47:13 CST 2016
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfos.file_path
     *
     * @return the value of fileinfos.file_path
     *
     * @mbggenerated Wed Apr 13 15:47:13 CST 2016
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfos.file_path
     *
     * @param filePath the value for fileinfos.file_path
     *
     * @mbggenerated Wed Apr 13 15:47:13 CST 2016
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfos.enduser_id
     *
     * @return the value of fileinfos.enduser_id
     *
     * @mbggenerated Wed Apr 13 15:47:13 CST 2016
     */
    public Long getEnduserId() {
        return enduserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfos.enduser_id
     *
     * @param enduserId the value for fileinfos.enduser_id
     *
     * @mbggenerated Wed Apr 13 15:47:13 CST 2016
     */
    public void setEnduserId(Long enduserId) {
        this.enduserId = enduserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfos.group_id
     *
     * @return the value of fileinfos.group_id
     *
     * @mbggenerated Wed Apr 13 15:47:13 CST 2016
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfos.group_id
     *
     * @param groupId the value for fileinfos.group_id
     *
     * @mbggenerated Wed Apr 13 15:47:13 CST 2016
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfos.save_date
     *
     * @return the value of fileinfos.save_date
     *
     * @mbggenerated Wed Apr 13 15:47:13 CST 2016
     */
    public Date getSaveDate() {
        return saveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfos.save_date
     *
     * @param saveDate the value for fileinfos.save_date
     *
     * @mbggenerated Wed Apr 13 15:47:13 CST 2016
     */
    public void setSaveDate(Date saveDate) {
        this.saveDate = saveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfos.status
     *
     * @return the value of fileinfos.status
     *
     * @mbggenerated Wed Apr 13 15:47:13 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfos.status
     *
     * @param status the value for fileinfos.status
     *
     * @mbggenerated Wed Apr 13 15:47:13 CST 2016
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfos.note
     *
     * @return the value of fileinfos.note
     *
     * @mbggenerated Wed Apr 13 15:47:13 CST 2016
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfos.note
     *
     * @param note the value for fileinfos.note
     *
     * @mbggenerated Wed Apr 13 15:47:13 CST 2016
     */
    public void setNote(String note) {
        this.note = note;
    }
    
    @Transient
    private Integer page = 1;

    @Transient
    private Integer rows = 10;
    
    public Integer getPage() {
        return page;
    }

    public void setPage(Integer page) {
        this.page = page;
    }

    public Integer getRows() {
        return rows;
    }

    public void setRows(Integer rows) {
        this.rows = rows;
    }
}