server:
    port: 8083
    context-path: #不写应用根目录
    sessionTimeout: 30

logging:
    level:
        org.zhangmz.cymbidium: DEBUG

spring:
    datasource:
        name: cAuthority
        url: jdbc:mysql://localhost:3306/cymbidium?useUnicode=true&characterEncoding=utf-8
        username: cymbidium
        password: cymbidium
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    mvc:
        view:
            prefix: /templates/
            suffix: .ftl
    freemarker:
        cache: false
        request-context-attribute: request