server:
    port: 8085
    context-path: #不写应用根目录
    sessionTimeout: 30

logging:
    level:
        org.zhangmz.cymbidium: DEBUG

cymbidium:
    authority:
        url:
            login: http://localhost:8081/api/authoriry/login
            logout: http://localhost:8081/api/authoriry/logout
            islogin: http://localhost:8081/api/authoriry/islogin