server:
    # 改为batch后，该参数无用
    port: 8082
    context-path: #不写应用根目录
    sessionTimeout: 30

logging:
    level:
        org.zhangmz.cymbidium: DEBUG

spring:
    batch:
        # concurrent: false
        sayHelloTimeTask:
            cronExpression: "*/10 * * * * ?"        
    # 主数据源，默认的
    datasource:
        url: jdbc:mysql://localhost:3306/cymbidium1?useUnicode=true&characterEncoding=utf-8
        username: cymbidium1
        password: cymbidium1
        driver-class-name: com.mysql.jdbc.Driver

# 更多数据源
custom:
    datasource:
        names: ds1,ds2
        ds1:
            url: jdbc:mysql://localhost:3306/cymbidium1?useUnicode=true&characterEncoding=utf-8
            username: cymbidium1
            password: cymbidium1
            driver-class-name: com.mysql.jdbc.Driver
        ds2:
            url: jdbc:mysql://localhost:3306/cymbidium2?useUnicode=true&characterEncoding=utf-8
            username: cymbidium2
            password: cymbidium2
            driver-class-name: com.mysql.jdbc.Driver
