server:
    # 改为batch后，该参数无用
    port: 18080
    context-path: #不写应用根目录
    sessionTimeout: 30

logging:
    level:
        org.zhangmz.cymbidium: DEBUG

spring:
    batch:
        # concurrent: false
        sayHelloTimeTask:
            cronExpression: "*/10 * * * * ?"
